name: Imhotep - Data Analytics Platform by Indeed
# http://stackoverflow.com/questions/10759577/underscore-issues-jekyll-redcarpet-github-flavored-markdown
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM #Enable GitHub Flavored Markdown (fenced code blocks)
    auto_ids: true
    hard_wrap: false
    syntax_highlighter: rouge

    exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile.rb', 'README.md']

# jekyll serve --watch --baseurl=
# baseurl: "https://indeedeng.github.io/imhotep"
# baseurl: "https://agrover-indeed.github.io/imhotep"
  baseurl: "https://alette-indeed.github.io/imhotep-my-fork
# permalinks are relative to their parent folder
#relative_permalinks: false
